- hosts: all
  tasks:

    - name: Read IP address
      command: "awk '!/127.0./ && /{{ ansible_hostname }}/ { print $1 }' /etc/hosts"
      register: ip_address

    - name: Configure novajoin
      command: >
        novajoin-install --debug --principal admin --password password
        --user stack --nova-password {{ devstack_localrc.SERVICE_PASSWORD }}
        --keystone-auth-url http://{{ ip_address.stdout }}/identity
      become: true

#    - name: Start novajoin service
