- project:
    check:
      jobs:
        - novajoin-functional:
            voting: false

- job:
    name: novajoin-functional
    description: |
      Run functional tests for novajoin.
    parent: devstack-tox-base
    nodeset: devstack-single-node-centos-7
    pre-run: playbooks/functional/pre.yaml
    run: playbooks/functional/run.yaml
    post-run: playbooks/functional/post.yaml
    vars:
      devstack_services:
        # FreeIPA is using Apache with TLS
        tls-proxy: false
        # Disable Swift services
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        # Disable Cinder services
        c-api: false
        c-bak: false
        c-sch: false
        c-vol: false
        cinder: false
    group-vars:
      # This job runs single node, but for completeness:
      subnode:
        devstack_services:
          # FreeIPA is using Apache with TLS
          tls-proxy: false
          # Disable Swift services
          # s-*: false
          # Disable Cinder services
          c-bak: false
          c-vol: false
